#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Detect Ethernet interface
ETH_IFACE=$(ip link show | awk '/^[0-9]+:/{iface=$2} /link\/ether/{print iface; exit}' | tr -d ':')

if [ -z "$ETH_IFACE" ]; then
    echo "❌ No Ethernet interface found on PC!"
    exit 1
fi

echo "========================================"
echo " WIRED 802.1X HOSTAPD SETUP (DIRECT LAN)"
echo "========================================"
echo "Ethernet Interface : $ETH_IFACE"
echo "Static PC IP       : 192.168.100.1/24"
echo ""

# Install hostapd if not present
if ! dpkg -s hostapd &>/dev/null 2>&1; then
    echo "[+] Installing hostapd..."
    sudo apt update -qq
    sudo apt install -y hostapd
else
    echo "✅ hostapd already installed"
fi

# Configure static IP on PC Ethernet interface
echo "[+] Assigning static IP 192.168.100.1 to $ETH_IFACE..."
sudo ip addr flush dev "$ETH_IFACE" || true
sudo ip addr add 192.168.100.1/24 dev "$ETH_IFACE"
sudo ip link set "$ETH_IFACE" up

# Generate hostapd wired configuration
HOSTAPD_CONF="$SCRIPT_DIR/hostapd_wired.conf"
cat > "$HOSTAPD_CONF" << EOF
# hostapd wired 802.1X authenticator config
# Generated by setup_wired_hostapd.sh

interface=$ETH_IFACE
driver=wired
logger_syslog=-1
logger_stdout=-1
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

ieee8021x=1
eap_reauth_period=3600

# RADIUS server (FreeRADIUS running on localhost)
auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=testing123

eapol_version=2
EOF

echo "✅ hostapd wired config generated at $HOSTAPD_CONF"
echo ""
echo "========================================"
echo " IMPORTANT: ANDROID DEVICE IP SETUP"
echo "========================================"
echo "Run this command via ADB to assign static IP to your Android device:"
echo "    adb shell ip addr flush dev eth0"
echo "    adb shell ip addr add 192.168.100.2/24 dev eth0"
echo "    adb shell ip link set eth0 up"
echo ""

echo "========================================"
echo " STARTING HOSTAPD IN WIRED MODE"
echo "========================================"
sudo hostapd "$HOSTAPD_CONF"
